### ISSUE TITLE
:unneeded is deprecated

### ISSUE THREAD

**Issue by marioleed** [launchdarkly/homebrew-tap#9]
Seems like unneeded bottles are deprecated now https://github.com/Homebrew/brew/commit/f65d525693a45c8e4c2ebc1452080f08c363ee15#diff-f12455e8eb757e3223300c7c544b5b752394173c2a9bb0440443d5673b151fb3

This tap outputs this warning in latest homebrew version:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the launchdarkly/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/launchdarkly/homebrew-tap/Formula/ld-find-code-refs.rb:6
```

Could you remove that property and update the tap?

**Comment by estraph** [comment]
I made a PR for removing the offending line from the formula, in case anyone can merge it? https://github.com/launchdarkly/homebrew-tap/pull/10

**Comment by estraph** [comment]
CC @atrakh @InTheCloudDan - apologies for the ping, but it doesn't seem like this repo is monitored very closely so I hope to get some human attention this way.

**Comment by atrakh** [comment]
Hi @estraph -- I am no longer a maintainer for LaunchDarkly projects. Your best bet would be to reach out to an active maintainer of [ld-find-code-refs](https://github.com/launchdarkly/ld-find-code-refs)

**Comment by InTheCloudDan** [comment]
@estraph sorry for the delay here. I've gone ahead and merged the change and set notifications for issues in the future. Thank you!
